export const FIND_MOVIE = 'FIND_MOVIE';
export const FIND_MOVIE_SUCCESS = 'FIND_MOVIE_SUCCESS';
export const FIND_MOVIE_FAILURE = 'FIND_MOVIE_FAILURE';
export const FIND_DETAIL = 'FIND_DETAIL';
export const FIND_DETAIL_SUCCESS = 'FIND_DETAIL_SUCCESS';
export const FIND_DETAIL_FAILURE = 'FIND_DETAIL_FAILURE';
